version: '3.7'
services:
  bet-maker-db:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
    container_name: bet_maker_db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - bet_maker_db_network
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  bet-maker:
    build:
      context: .
      dockerfile: src/bet_maker/Dockerfile
    ports:
      - "8001:8001"
    restart: always
    env_file:
      - .env
    container_name: bet_maker
    networks:
      - bet_maker_db_network
      - bet_maker_network
    depends_on:
      - bet-maker-db
    command: sh -c "alembic upgrade head && uvicorn src.bet_maker.main:app --host 0.0.0.0 --port 8001"

  line-provider:
    build:
      context: .
      dockerfile: src/line_provider/Dockerfile
    ports:
      - "8080:8080"
    restart: always
    networks:
      - bet_maker_network
    env_file:
      - .env
    container_name: line_provider
    
volumes:
  bet_maker_db:
  line_provider:

networks:
  bet_maker_network:
  bet_maker_db_network:
